#!/bin/bash
# IrisQuant Monitoring & Auto-Restart Script
# Generated by Iris Agent

LOG_FILE="/root/irisquant/logs/auto_monitor.log"
mkdir -p /root/irisquant/logs

echo "$(date) - Starting Monitor" >> $LOG_FILE

# List of agents to monitor
AGENTS=$(pm2 jlist | jq -r '.[] | select(.pm2_env.status == "errored" or .pm2_env.status == "stopped") | .name')

for AGENT in $AGENTS; do
    RESTARTS=$(pm2 jlist | jq -r ".[] | select(.name == "$AGENT") | .pm2_env.restart_time")
    
    # Check if restart count is too high (logic handled by Iris agent turn, but logging here)
    echo "$(date) - Agent $AGENT found in status errored/stopped. Restart count: $RESTARTS" >> $LOG_FILE
    
    # Trigger Iris to handle specific fixes
done
